// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPHuUZ-XwAZIRNkNk528aCAp0Op2Mm2_8',
    appId: '1:1006814341578:web:ca9c0d25328c0d4a650733',
    messagingSenderId: '1006814341578',
    projectId: 'messmate-479e1',
    authDomain: 'messmate-479e1.firebaseapp.com',
    storageBucket: 'messmate-479e1.firebasestorage.app',
    measurementId: 'G-CE82Q1VK66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSYLVFJkYTuWb7463hi6AtKn-tVbWL8pQ',
    appId: '1:1006814341578:android:a7a03b6cb798988f650733',
    messagingSenderId: '1006814341578',
    projectId: 'messmate-479e1',
    storageBucket: 'messmate-479e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm6oAvi3Cc3rzXaGRV6MyXS17INNxf94s',
    appId: '1:1006814341578:ios:ea4948ceee69442d650733',
    messagingSenderId: '1006814341578',
    projectId: 'messmate-479e1',
    storageBucket: 'messmate-479e1.firebasestorage.app',
    iosBundleId: 'com.example.messmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm6oAvi3Cc3rzXaGRV6MyXS17INNxf94s',
    appId: '1:1006814341578:ios:ea4948ceee69442d650733',
    messagingSenderId: '1006814341578',
    projectId: 'messmate-479e1',
    storageBucket: 'messmate-479e1.firebasestorage.app',
    iosBundleId: 'com.example.messmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPHuUZ-XwAZIRNkNk528aCAp0Op2Mm2_8',
    appId: '1:1006814341578:web:67f3e83e603f271e650733',
    messagingSenderId: '1006814341578',
    projectId: 'messmate-479e1',
    authDomain: 'messmate-479e1.firebaseapp.com',
    storageBucket: 'messmate-479e1.firebasestorage.app',
    measurementId: 'G-YKX096S8WD',
  );
}
